name: commerce_proxi_ia_mobile
description: Application mobile Flutter pour l'automatisation commerciale avec IA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.2
  flutter_material_symbols: ^1.0.0
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts & Data Visualization
  fl_chart: ^0.65.0
  
  # Image & Media
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  
  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Biometrics
  local_auth: ^2.1.7
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700







